<?php
set_include_path(get_include_path() . PATH_SEPARATOR . dirname(__FILE__) . DIRECTORY_SEPARATOR . 'libpy2php');
require_once('libpy2php.php');
require_once( 'os_path.php');
$dir = os_path::realpath('.');
pyjslib_printnl(os_path::isdir($dir));
pyjslib_printnl(os_path::isfile($dir));
pyjslib_printnl(os_path::islink($dir));
pyjslib_printnl([os_path::split($dir)[0], os_path::split($dir)[1]], true);
pyjslib_printnl(os_path::join('/' . os_path::split($dir)[0] . '/', os_path::split($dir)[1]));
$path = os_path::abspath('./os.path.py');
pyjslib_printnl($path);
pyjslib_printnl(os_path::basename($path));
pyjslib_printnl(os_path::commonprefix([$dir, $path]));
pyjslib_printnl(os_path::dirname($path));
pyjslib_printnl(os_path::exists($path));
pyjslib_printnl(os_path::expanduser('~/Desktop'));
pyjslib_printnl(os_path::expandvars('$HOME, $SHELL, ${HOME}, ${SHELL}'));
pyjslib_printnl(pyjslib_int(os_path::getatime($path)));
pyjslib_printnl(pyjslib_int(os_path::getmtime($path)));
pyjslib_printnl(pyjslib_int(os_path::getctime($path)));
pyjslib_printnl(os_path::getsize($path));
pyjslib_printnl(os_path::isabs($path));
pyjslib_printnl(os_path::isfile($path));
pyjslib_printnl(os_path::normcase($path));
pyjslib_printnl(os_path::realpath($path));
pyjslib_printnl(os_path::samefile($path, $path));
$parts = os_path::splitext($path);
pyjslib_printnl([$parts[0], $parts[1]], true);

